import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Plus, FileText } from "lucide-react";
import { googleSheetsService } from "@/lib/google-sheets";

export const revalidate = 0;

async function getReports() {
    try {
        const reportsData = await googleSheetsService.getSheetData("reports!A2:Z");
        
        if (!reportsData) return [];

        // reports: ['id', 'report_type', 'generated_by', 'period', 'file_path']
        return reportsData.map(r => ({
            id: r[0],
            report_type: r[1],
            generated_by: r[2],
            period: r[3],
            file_path: r[4]
        }));

    } catch (error) {
        console.error("Error fetching reports:", error);
        return [];
    }
}

export default async function ReportsPage() {
  const reports = await getReports();

  return (
    <div className="p-8 space-y-8">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Reports</h2>
          <p className="text-muted-foreground">
            Generate and view system reports.
          </p>
        </div>
        <Button>
          <Plus className="mr-2 h-4 w-4" /> Generate Report
        </Button>
      </div>

      <div className="rounded-md border">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Report Type</TableHead>
              <TableHead>Period</TableHead>
              <TableHead>Generated By</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {reports.length === 0 ? (
                <TableRow>
                    <TableCell colSpan={4} className="text-center h-24 text-muted-foreground">
                        No reports generated yet.
                    </TableCell>
                </TableRow>
            ) : (
                reports.map((report) => (
                <TableRow key={report.id}>
                    <TableCell className="font-medium flex items-center">
                        <FileText className="mr-2 h-4 w-4 text-blue-500" />
                        {report.report_type}
                    </TableCell>
                    <TableCell>{report.period}</TableCell>
                    <TableCell>{report.generated_by}</TableCell>
                    <TableCell className="text-right">
                    <Button variant="ghost" size="sm">
                        Download
                    </Button>
                    </TableCell>
                </TableRow>
                ))
            )}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}
